server:
  port: 80

spring:
  jpa:
    show-sql: false
  datasource:
    url: "jdbc:postgresql://93.90.205.170/freyafitness"
    username: ${DB_USR}
    password: ${DB_PSW}

mail:
  url: http://freya.fitness:7700
