server:
  port: 9000
  session:
    cookie:
      name: UISESSION
spring:
  data:
    rest:
      base-path: /api
  thymeleaf:
    check-template: true
    check-template-location: true
    prefix: classpath:/static/
    cache: false
  jackson:
    serialization:
      write_dates_as_timestamps: false
  datasource:
    url: jdbc:postgresql://localhost/freyafitness
    #url: jdbc:postgresql://93.90.205.170/freyafitness
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
security:
  basic:
    enabled: true
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://127.0.0.1:9000/oauth/token
      userAuthorizationUri: http://127.0.0.1:9000/oauth/authorize
    resource:
      userInfoUri: http://localhost:9000/auth/user/me
course:
  create:
    minutes: 60
    maxParticipants: 12
mail:
  resetpassword:
    success: Erfolg
    invalid: Nicht so erfolgreich
    sender: admin@freya.fitness
    subject: Passwort für freya.fitness zurücksetzen
    message: Bla bla bla
    validity:
      hours: 24
