server:
  port: ${APP_PORT_S:9443}
  ssl:
    key-store: classpath:my.p12
    key-store-password: ${SSL_PSW}
    key-store-type: PKCS12
    key-alias: freyafitness
  session:
    cookie:
      name: UISESSION
spring:
  data:
    rest:
      base-path: /api
  thymeleaf:
    check-template: true
    check-template-location: true
    prefix: classpath:/static/
    cache: false
  jackson:
    serialization:
      write_dates_as_timestamps: false
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        temp:
          # Disable feature detection by this undocumented parameter.
          # Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
          use_jdbc_metadata_defaults: false
    # Because detection is disabled you have to set correct dialect by hand.
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
course:
  create:
    minutes: 60
    maxParticipants: 12
mail:
  sender: FreyRaum <admin@freya.fitness>
  develop:
    receiver: develop@freya.fitness
  resetpassword:
    success: Erfolg
    invalid: Nicht so erfolgreich
    subject: Passwort für freya.fitness zurücksetzen
    message:
    validity:
      hours: 24