server:
  ssl:
    key-store-password: ${SSL_PSW}

spring:
  jpa:
    show-sql: false
  datasource:
    url: "jdbc:postgresql://93.90.205.170/freyafitness"
    username: ${DB_USR}
    password: ${DB_PSW}

zuul:
  routes:
    news:
      url: http://freya.fitness:7800/news/
    exercises:
      url: http://freya.fitness:7800/exercises/
    frontend:
      url: http://freya.fitness:3333/
mail:
  url: http://freya.fitness:7700
