server:
  port: 9443
  ssl:
    key-store: classpath:my.p12
    key-store-password: test
    key-store-type: PKCS12
    key-alias: freyafitness
  session:
    cookie:
      name: UISESSION
zuul:
  ignoredPatterns:
    - /oauth/**
    - /user/**
    - /contact/**
    - /courses/**
    - /coursetypes/**
    - /memberships/**
    - /membershiptypes/**
    - /participations/**
    - /password/**
    - /preferences/**
    - /profile/**
    - /statistics/**
  routes:
    news:
      sensitiveHeaders:
      path: /news/**
      url: http://localhost:7800/news/
    frontend:
      sensitiveHeaders:
      path: /**
      url: http://localhost:3333
spring:
  data:
    rest:
      base-path: /api
  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
  thymeleaf:
    check-template: true
    check-template-location: true
    prefix: classpath:/static/
    cache: false
  jackson:
    serialization:
      write_dates_as_timestamps: false
  datasource:
    url: jdbc:postgresql://localhost/freyafitness
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        temp:
          # Disable feature detection by this undocumented parameter.
          # Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
          use_jdbc_metadata_defaults: false
    # Because detection is disabled you have to set correct dialect by hand.
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
course:
  create:
    minutes: 60
    maxParticipants: 12
mail:
  url: http://freya.fitness:7700
  sender: FreyRaum <admin@freya.fitness>
  develop:
    receiver: develop@freya.fitness
  resetpassword:
    success: Erfolg
    invalid: Nicht so erfolgreich
    subject: Passwort für freya.fitness zurücksetzen
    message:
    validity:
      hours: 24
  contact:
    receiver: freyraum@freya.fitness
  account_created:
    receiver: freyraum@freya.fitness
