node {
    checkout scm
    stage('lnode setup'){
        sh './gradlew nodeSetup'
    }
    stage('compile') {
        parallel(
            java: {
                sh './gradlew clean build'
            },
            npm: {
                sh './gradlew npmInstall'
            }
        )
    }
    stage('test') {
        parallel(
            jUnit: {
                sh './gradlew test'
            },
            jest: {
                sh './gradlew npmTest'
            }
        )
    }
    stage('build webapp') {
        sh './gradlew npmProd'
    }
    stage('deployment') {
        echo 'deployment'
    }
}