node {
    stage('checkout') {
        echo 'checkout'
    }
    stage('compile') {
        sh './gradlew clean build'
    }
    stage('test') {
        parallel {
            jest: {
                sh './gradlew npmTest'
            },
            jUnit: {
                sh './gradlew test'
            }
        }
    }
    stage('deployment') {
        echo 'deployment'
    }
}